### ISSUE TITLE
[ICS02] [ICS03] Missing `ClientType`, `ClientId` validation checks

### ISSUE THREAD

**Issue by Farhad-Shabani** [cosmos/ibc-rs#621] opened 2023-04-13 20:26 UTC
## Summary
Part of #233

- Some IBC messages take in `client_state` as `Any` and the correctness of their included `ClientType` is not checked. 
E.g. client creation handler is missing that.

- Given that the `ClientType` is a part of the client identifier constructor, some `ClientId` checks are missing too.

- Similar check in IBC-go is carried out by [`ValidateClientType`](https://github.com/cosmos/ibc-go/blob/a24a6c65f14ceee5e9c8dd3f0f79d63439f1db23/modules/core/02-client/types/client.go#L87-L111)

**Comment by plafer** [comment] 2023-04-14 18:51
This is called in [`MsgCreateClient::ValidateBasic()`](https://github.com/cosmos/ibc-go/blob/d3038f8317bbf4a9f43c578f7b6d4a6a5c4ebda5/modules/core/02-client/types/msgs.go#L68), so IIUC this issue is a subset of (and therefore a duplicate of) #233

**Comment by Farhad-Shabani** [comment] 2023-04-18 02:56
> This is called in [`MsgCreateClient::ValidateBasic()`](https://github.com/cosmos/ibc-go/blob/d3038f8317bbf4a9f43c578f7b6d4a6a5c4ebda5/modules/core/02-client/types/msgs.go#L68), so IIUC this issue is a subset of (and therefore a duplicate of) #233

Regarding #233, we ideally should go through a list of necessary checks and add any missed validation steps by calling/importing relevant ready-to-go functions or error variants. As for the `ClientType`, There isn't such a callable method. So, even though this issue is implicitly part of that, I wanted first to get on the same page about what a valid `ClientType` string looks like. Plus, breaking down the changes into smaller, more specific chunks, so we could keep things clearer for the review.

**Closed as completed** 2023-05-01 21:27 UTC
Labels: A: bug, A: breaking
